#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: wildcards
  namespace: apps
spec:
  delegations:
    - secretName: #@ "apps.{}".format(data.values.domain)
      targetNamespaces:
        - "*"
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: wildcards
  namespace: default
spec:
  delegations:
    - secretName: #@ "default.{}".format(data.values.domain)
      targetNamespaces:
        - "*"
