#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")

#@ foundation = "dev"

#@ secretConfig = "#@data/values\n---\n" + yaml.encode(library.get(foundation).eval())
#@ 
#@ config = overlay.apply(data.values, secretConfig)

---
apiVersion: v1
kind: Namespace
metadata:
  name: sso
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: dex
  namespace: sso
spec:
  virtualhost:
    fqdn: #@ "login.sso.{}".format(config.domain)
    tls:
      secretName: #@ "sso/sso.{}".format(config.domain)
  routes:
    - services:
        - name: dex
          port: 32000

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: dex
    helm.sh/chart: dex-2.10.0
    app.kubernetes.io/instance: dex
    app.kubernetes.io/version: 2.23.0
    app.kubernetes.io/managed-by: Helm
  annotations:
    kapp.k14s.io/versioned: ""
    kapp.k14s.io/num-versions: "4"
  name: dex
  namespace: sso
stringData:
  #@yaml/text-templated-strings
  config.yaml: |
    issuer: https://login.sso.(@= config.domain @)
    frontend:
      theme: tkg
    web:
      http: 0.0.0.0:5556
    expiry:
      signingKeys: "10m"
      idTokens: "5m"
    logger:
      level: "debug"
      format: "json"
    oauth2:
      skipApprovalScreen: true
    storage:
      type: kubernetes
      config:
        inCluster: true
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: (@= config.github_client_id @)
        clientSecret: (@= config.github_client_secret @)
        redirectURI: https://login.sso.(@= config.domain @)/callback
        orgs: 
        - name: (@= config.github_org @)
        - name: (@= config.github_org @)-Teams
          teams:
          - (@= config.github_team @)
    - type: saml
      id: saml
      name: SAML
      config:
        ssoURL: (@= config.saml_url @)
        caData: (@= config.saml_caData @)
        usernameAttr: name
        emailAttr: email
        groupsAttr: groups
        redirectURI: https://login.sso.(@= config.domain @)/callback
    staticClients:
    - id: (@= config.sonarqube_client_id @)
      secret: (@= config.sonarqube_client_secret @)
      name: 'SonarQube'
      redirectURIs:
      - 'https://sonar.apps.(@= config.domain @)/oauth2/callback'
    - id: (@= config.kuard_client_id @)
      secret: (@= config.kuard_client_secret @)
      name: 'Kuard'
      redirectURIs:
      - 'https://kuard.apps.(@= config.domain @)/oauth2/callback'
    - id: (@= config.grafana_client_id @)
      secret: (@= config.grafana_client_secret @)
      name: 'Grafana'
      redirectURIs:
      - 'https://grafana.monitoring.(@= config.domain @)/login/generic_oauth'