#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: storageclass
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller-clusteradmin
  fetch:
  - git:
      url: #@ data.values.git_url
      ref: #@ data.values.git_branch
      subPath: workload/storageclass/manifests
      secretRef:
        name: #@ data.values.git.secretRef
  template:
  - ytt:
      ignoreUnknownComments: true
  deploy:
  - kapp: {}