#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cert-manager
  namespace: kapp-controller
  annotations:
    kapp.k14s.io/change-group: "gitops.tanzu.vmware.com/cert-manager"
spec:
  serviceAccountName: kapp-controller-clusteradmin
  fetch:
  - git:
      url: #@ data.values.git_url
      ref: #@ data.values.git_branch
      subPath: workload/cert-manager/manifests
      secretRef:
        name: #@ data.values.git.secretRef
  template:
  - ytt:
      ignoreUnknownComments: true
  - kbld: {}
  deploy:
  - kapp:
      delete:
        rawOptions: 
        - "--apply-ignored=true"