#@data/values
---

git:
  url: https://code.afcmade.com/chrysalis/tkg-clusters.git
  branch: origin/default
  secretRef: management-git-secret

workload_secretRef:
  #! This file contains secrets for configuring workload clusters.
  - workload-config-secrets
  - workload-git-secrets