---
apiVersion: v1
kind: Secret
metadata:
  name: workload-config-secrets
  namespace: workload-clusters
stringData:
  zzauthsecrets.yaml: |
    #@data/values
    ---
    oidc:
      client_id: REMOVED
      issuer_url: https://planetvoor.auth0.com
    etcd:
      aescbc: ENCRYPTIONKEY
---
apiVersion: v1
kind: Secret
metadata:
  name: workload-git-secrets
  namespace: workload-clusters
stringData:
  git-secrets.yaml: |
    #@data/values
    ---
    domain: tanzu.world
---
apiVersion: v1
kind: Secret
metadata:
  name: management-git-secret
  namespace: workload-clusters
stringData:
  username: voor-cibot
  password: REMOVED
