---
apiVersion: v1
kind: Secret
metadata:
  name: workload-clusters-secrets
  namespace: workload-clusters
stringData:
  workload-cluster-secrets.yaml: |
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: domain-values
      namespace: kapp-controller
    stringData:
      serving-values.yaml: |
        #@data/values
        ---
        domain: tanzu.world
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: grafana-client-values
      namespace: kapp-controller
    stringData:
      grafana-client-values.yaml: |
        #@data/values
        ---
        grafana_client_id: grafana-client
        grafana_client_secret: REMOVED
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: github-client-values
      namespace: kapp-controller
    stringData:
      github-client-values.yaml: |
        #@data/values
        ---
        github_client_id: REMOVED
        github_client_secret: REMOVED
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: dex-saml-values
      namespace: kapp-controller
    stringData:
      dex-saml-values.yaml: |
        #@data/values
        ---
        saml_url: https://planetvoor.auth0.com/samlp/REMOVED
        saml_caData: REMOVED 
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: sonarqube-client-values
      namespace: kapp-controller
    stringData:
      sonarqube-client-values.yaml: |
        #@data/values
        ---
        sonarqube_client_id: sonarqube-client
        sonarqube_client_secret: REMOVED
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: kuard-client-values
      namespace: kapp-controller
    stringData:
      kuard-client-values.yaml: |
        #@data/values
        ---
        kuard_cookie_secret: REMOVED
        kuard_client_id: kuard-client
        kuard_client_secret: REMOVED
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: certmanager-values
      namespace: kapp-controller
    stringData:
      cert-manager-values.yaml: |
        #@data/values
        ---
        acme_email: rcanvo@gmail.com
        acme_url: "https://acme-v02.api.letsencrypt.org/directory"
        cloudflare_token: REMOVED
    ---
    apiVersion: v1
    data:
      tls.crt: REMOVED
      tls.key: REMOVED
    kind: Secret
    metadata:
      labels:
        sealedsecrets.bitnami.com/sealed-secrets-key: active
      name: sealed-secrets-keywg6gr
      namespace: kube-system
    type: kubernetes.io/tls
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: gangway-values
      namespace: kapp-controller
    stringData:
      gangway-values.yaml: |
        #@data/values
        ---
        auth:
          clientID: "REMOVED"
          clientSecret: "REMOVED"
          sesssionKey: "REMOVED="
          authorizeURL: "https://example.auth0.com/authorize"
          tokenURL: "https://example.auth0.com/oauth/token"
          audience: "https://example.auth0.com/userinfo"
          redirectURL: "https://sso.management.tanzu.world/callback"
          usernameClaim: "sub"
          emailClaim: "email"

        management:
          cluster_name: "acluster"
          apiServerURL: "https://example.us-gov-east-1.elb.amazonaws.com:6443"
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: aws-values
      namespace: kapp-controller
    stringData:
      aws-values.yaml: |
        #@data/values
        ---
        aws_region: "us-gov-east-1"
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: external-dns-values
      namespace: kapp-controller
    stringData:
      external-dns-values.yaml: |
        #@data/values
        ---
        assumed_role: ""
        pod_role: "arn:aws-us-gov:iam:::role/internalhostedzone.pod.tkg.tanzu"
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: kiam-values
      namespace: kapp-controller
    stringData:
      kiam-values.yaml: |
        #@data/values
        ---
        kiam_role_arn: "kiam-server.cluster-api-provider-aws.sigs.k8s.io"
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: workload-git-secret
      namespace: kapp-controller
    stringData:
      username: voor-cibot
      password: REMOVED