#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"AWSCluster"}),expects="0+"
---
spec:
  #@overlay/match missing_ok=True
  controlPlaneLoadBalancer:
    #@overlay/match missing_ok=True
    scheme: #@ data.values.aws.controlPlaneLoadBalancer.scheme
