#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.not_op(overlay.subset({"apiVersion": "kapp.k14s.io/v1alpha1", "kind":"Config"})),expects="0+"
---
#@overlay/match missing_ok=True
metadata:
  #@overlay/match missing_ok=True
  namespace: #@ data.values.aws.vpc.name

#@overlay/match by=overlay.subset({"kind":"Cluster"}),expects="0+"
---
spec:
  controlPlaneRef:
    #@overlay/match missing_ok=True
    namespace: #@ data.values.aws.vpc.name
  infrastructureRef:
    #@overlay/match missing_ok=True
    namespace: #@ data.values.aws.vpc.name

#@overlay/match by=overlay.subset({"kind":"AWSCluster"}),expects="0+"
---
spec:
  #@overlay/match missing_ok=True
  region: #@ data.values.aws.region
  #@overlay/match missing_ok=True
  sshKeyName: #@ data.values.aws.sshKeyName
  #@overlay/match missing_ok=True
  networkSpec:
    #@overlay/match missing_ok=True
    subnets:
    #@ for subnet in data.values.aws.subnets:
    #@overlay/match by="id", missing_ok=True
    #@overlay/match-child-defaults missing_ok=True
    - id: #@ subnet
    #@ end
    vpc:
      #@overlay/match missing_ok=True
      #@overlay/remove
      cidrBlock:
      #@overlay/match missing_ok=True
      id: #@ data.values.aws.vpc.id
  #@overlay/match missing_ok=True
  bastion:
    #@overlay/match missing_ok=True
    enabled: false
  #@overlay/match missing_ok=True
  additionalTags:
    #@overlay/match missing_ok=True
    Environment: #@ data.values.aws.vpc.name
    #@overlay/match missing_ok=True
    Responsibility: #@ data.values.team

#@overlay/match by=overlay.subset({"kind":"AWSMachineTemplate"}),expects="0+"
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      sshKeyName: #@ data.values.aws.sshKeyName


#@overlay/match by=overlay.subset({"kind":"KubeadmControlPlane"}),expects="0+"
---
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      controllerManager:
        #@overlay/match missing_ok=True
        extraArgs:
          #@overlay/match missing_ok=True
          configure-cloud-routes: "false"
