#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:yaml", "yaml")

#@ def host_config():
- hostnamectl set-hostname {{ v1.local_hostname }}.{{ v1.region }}.compute.internal
#@ end

#@overlay/match by=overlay.subset({"kind":"KubeadmControlPlane"}),expects="0+"
---
spec:
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        #@overlay/match missing_ok=True
        name: '{{ v1.local_hostname }}.{{ v1.region }}.compute.internal'
    clusterConfiguration:
      controllerManager:
        extraArgs:
          #@overlay/match missing_ok=True
          configure-cloud-routes: "false"
    joinConfiguration:
      nodeRegistration:
        #@overlay/match missing_ok=True
        name: '{{ v1.local_hostname }}.{{ v1.region }}.compute.internal'
    #@overlay/match missing_ok=True
    preKubeadmCommands: #@ host_config()

#@overlay/match by=overlay.subset({"kind":"KubeadmConfigTemplate"}),expects="0+"
---
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          #@overlay/match missing_ok=True
          name: '{{ v1.local_hostname }}.{{ v1.region }}.compute.internal'
      #@overlay/match missing_ok=True
      preKubeadmCommands: #@ host_config()