#@ load("@ytt:library", "library")
#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")
#@ load("@ytt:overlay", "overlay")

#@ load("calico/calico.lib.yaml", "calicoyaml")
#@ load("calico/calico_overlay.lib.yaml", "calicooverlay")

--- #@ template.replace(overlay.apply(calicoyaml(), calicooverlay()))