apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: oauth2-proxy
    chart: oauth2-proxy-3.2.2
    release: kuard-proxy
    heritage: Helm
  name: kuard-proxy-oauth2-proxy
  namespace: apps
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
    chart: oauth2-proxy-3.2.2
    release: kuard-proxy
    heritage: Helm
  name: kuard-proxy-oauth2-proxy
  namespace: apps
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: oauth2-proxy
    release: kuard-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
    chart: oauth2-proxy-3.2.2
    heritage: Helm
    release: kuard-proxy
  name: kuard-proxy-oauth2-proxy
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
      release: kuard-proxy
  template:
    metadata:
      annotations:
        checksum/config: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
        checksum/config-emails: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
        checksum/secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        checksum/google-secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      labels:
        app: oauth2-proxy
        release: kuard-proxy
    spec:
      serviceAccountName: kuard-proxy-oauth2-proxy
      containers:
      - name: oauth2-proxy
        image: quay.io/pusher/oauth2_proxy:v5.1.0
        imagePullPolicy: IfNotPresent
        args:
        - --http-address=0.0.0.0:4180
        - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: kuard-proxy-oauth2-proxy
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kuard-proxy-oauth2-proxy
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: kuard-proxy-oauth2-proxy
              key: cookie-secret
        ports:
        - containerPort: 4180
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          timeoutSeconds: 1
          successThreshold: 1
          periodSeconds: 10
        resources: {}
        volumeMounts:
        - mountPath: /etc/oauth2_proxy
          name: configmain
        securityContext:
          runAsNonRoot: true
      volumes:
      - configMap:
          defaultMode: 420
          name: kuard-proxy-oauth2-proxy
        name: configmain
      tolerations: []
