apiVersion: kapp.k14s.io/v1alpha1
kind: Config

rebaseRules:

# clusterctl label
- path: [metadata, labels, clusterctl.cluster.x-k8s.io]
  type: copy
  sources: [new, existing]
  resourceMatchers: &group
  - allMatcher: {}

- path: [metadata, labels, clusterctl.cluster.x-k8s.io/lifecycle]
  type: copy
  sources: [new, existing]
  resourceMatchers: *group