#@data/values
---

domain: ""

team: demo

kubeadmConfigSpec:
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  imageRepository: registry.tkg.vmware.run
  kubernetesVersion: v1.19.1+vmware.3
  etcd:
    local:
      dataDir: /var/lib/etcd
      imageRepository: registry.tkg.vmware.run
      imageTag: v3.4.13_vmware.2
  dns:
    type: CoreDNS
    imageRepository: registry.tkg.vmware.run
    imageTag: v1.7.0_vmware.3
  ntp:
    servers:
    - 169.254.169.123

aws:
  region: us-gov-east-1
  sshKeyName: default
  vpc:
    name: workload-clusters
    id: "vpc-077617e1cf2cfb9ac"
  subnets:
  - subnet-0b9f0a52213fb7d93
  - subnet-01f5b8ce2d88cfcce
  ami:
    id: "ami-0b67bd0ee39c2cba5"
  controlPlaneLoadBalancer:
    scheme: internet-facing

oidc:
  client_id: ""
  issuer_url: ""
  username_claim: email
  groups_claim: groups

etcd:
  aescbc: ""
