apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: generic
  annotations:
    kapp.k14s.io/update-strategy: 'always-replace'
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer