apiVersion: kapp.k14s.io/v1alpha1
kind: Config

rebaseRules:

# clusterctl label
- path: [metadata, labels, clusterctl.cluster.x-k8s.io]
  type: copy
  sources: [new, existing]
  resourceMatchers: &group
  - allMatcher: {}
  # - apiVersionKindMatcher: {apiVersion: apiextensions.k8s.io/v1beta1, kind: CustomResourceDefinition}
  # - apiVersionKindMatcher: {apiVersion: apiextensions.k8s.io/v1, kind: CustomResourceDefinition}
  # - apiVersionKindMatcher: {apiVersion: v1, kind: Namespace}
  # - apiVersionKindMatcher: {apiVersion: rbac.authorization.k8s.io/v1, kind: ClusterRole}
  # - apiVersionKindMatcher: {apiVersion: rbac.authorization.k8s.io/v1, kind: Role}
  # - apiVersionKindMatcher: {apiVersion: rbac.authorization.k8s.io/v1, kind: ClusterRoleBinding}
  # - apiVersionKindMatcher: {apiVersion: rbac.authorization.k8s.io/v1, kind: RoleBinding}

- path: [metadata, labels, clusterctl.cluster.x-k8s.io/lifecycle]
  type: copy
  sources: [new, existing]
  resourceMatchers: *group

# crd conversions
- path: [spec, conversion, conversionReviewVersions]
  type: copy
  sources: [new, existing]
  resourceMatchers: &crd
  - apiVersionKindMatcher: {apiVersion: apiextensions.k8s.io/v1, kind: CustomResourceDefinition}

- path: [spec, conversion, webhookClientConfig, service, port]
  type: copy
  sources: [new, existing]
  resourceMatchers: *crd

- path: [spec, conversion, webhookClientConfig, caBundle]
  type: copy
  sources: [new, existing]
  resourceMatchers: *crd

- path: [spec, version]
  type: copy
  sources: [new, existing]
  resourceMatchers: *crd

- path: [spec, conversion, webhook, clientConfig, service, port]
  type: copy
  sources: [new, existing]
  resourceMatchers: *crd

# ignore bootstrap credentials, they are dynamically updated
- path: [data, credentials]
  type: copy
  sources: [existing]
  resourceMatchers:
  - kindNamespaceNameMatcher: {kind: Secret, namespace: capa-system, name: capa-manager-bootstrap-credentials}