apiVersion: kapp.k14s.io/v1alpha1
kind: Config

rebaseRules:

# clusterctl label
- paths:
  - [metadata, labels, clusterctl.cluster.x-k8s.io]
  - [metadata, labels, clusterctl.cluster.x-k8s.io/lifecycle]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - allMatcher: {}
  
# ignore bootstrap credentials, they are dynamically updated
- path: [data, credentials]
  type: copy
  sources: [existing]
  resourceMatchers:
  - kindNamespaceNameMatcher: {kind: Secret, namespace: capa-system, name: capa-manager-bootstrap-credentials}