apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonarqube-sonarqube
  namespace: sonar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-sonarqube-config
  labels:
    app: sonarqube
    chart: sonarqube-6.6.0
    release: sonarqube
    heritage: Helm
  namespace: sonar
data:
  sonar.properties: |-
    sonar.core.serverBaseURL=sonar.apps.tanzu.world
    sonar.web.sso.enable=true
    sonar.web.sso.loginHeader=X-Forwarded-Email
    sonar.web.sso.nameHeader=X-Forwarded-Preferred-Username
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-sonarqube-copy-plugins
  labels:
    app: sonarqube
    chart: sonarqube-6.6.0
    release: sonarqube
    heritage: Helm
  namespace: sonar
data:
  copy_plugins.sh: |-
    #!/bin/bash
    for f in /opt/sonarqube/extensions/plugins/tmp/*.jar
    do
      file=${f##*/} && file=${file%-[0-9]*}
      for original in /opt/sonarqube/extensions/plugins/*.jar
      do
        originalfile=${original##*/} && originalfile=${originalfile%-[0-9]*}
        if [ "$originalfile" == "$file" ]; then
          rm -f "$original"
        fi
      done
    done
    cp /opt/sonarqube/extensions/plugins/tmp/*.jar /opt/sonarqube/extensions/plugins/
    exec /opt/sonarqube/bin/run.sh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-sonarqube-install-plugins
  labels:
    app: sonarqube
    chart: sonarqube-6.6.0
    release: sonarqube
    heritage: Helm
  namespace: sonar
data:
  install_plugins.sh: cd /opt/sonarqube/extensions/plugins/tmp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-sonarqube-postgres-config
  labels:
    app: sonarqube
    chart: sonarqube-6.6.0
    release: sonarqube
    heritage: Helm
  namespace: sonar
data:
  SONARQUBE_JDBC_USERNAME: sonarUser
  SONARQUBE_JDBC_URL: jdbc:postgresql://sonarqube-db-postgresql:5432/sonarDB
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-sonarqube
  labels:
    app: sonarqube
    chart: sonarqube-6.6.0
    release: sonarqube
    heritage: Helm
  namespace: sonar
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: generic
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-sonarqube
  labels:
    app: sonarqube
    chart: sonarqube-6.6.0
    release: sonarqube
    heritage: Helm
  namespace: sonar
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: sonarqube
    release: sonarqube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-sonarqube
  labels:
    app: sonarqube
    chart: sonarqube-6.6.0
    release: sonarqube
    heritage: Helm
  namespace: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
      release: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
        release: sonarqube
      annotations:
        checksum/plugins: 93d52379b10718202a0d61acdae98b65a5fb9c13e2d6fd79bd722759c88829d7
        checksum/config: fad6dd79dc92acbc25c49caf293424d3ba46d23dba6ab1c992bdf7a8673c9364
        checksum/secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    spec:
      serviceAccountName: sonarqube-sonarqube
      securityContext:
        fsGroup: 999
      initContainers:
      - name: init-sysctl
        image: busybox:1.31
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - if [[ "$(sysctl -n vm.max_map_count)" -lt 262144 ]]; then sysctl -w vm.max_map_count=262144; fi
      containers:
      - name: sonarqube
        image: sonarqube:8.2-community
        imagePullPolicy: null
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
        env:
        - name: SONARQUBE_WEB_JVM_OPTS
          value: ""
        - name: SONARQUBE_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube-passwords
              key: postgresql-password
        envFrom:
        - configMapRef:
            name: sonarqube-sonarqube-postgres-config
        livenessProbe:
          httpGet:
            path: /sessions/new
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /sessions/new
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 6
        volumeMounts:
        - mountPath: /opt/sonarqube/conf/
          name: config
        - mountPath: /opt/sonarqube/data
          name: sonarqube
          subPath: data
        - mountPath: /opt/sonarqube/extensions/plugins/tmp
          name: sonarqube
          subPath: tmp
        - mountPath: /opt/sonarqube/extensions/downloads
          name: sonarqube
          subPath: downloads
        - mountPath: /opt/sonarqube/temp
          name: sonarqube
          subPath: temp
        - mountPath: /opt/sonarqube/logs
          name: sonarqube
          subPath: logs
        - mountPath: /tmp
          name: tmp-dir
        - name: copy-plugins
          mountPath: /tmp/scripts
        resources: {}
      volumes:
      - name: config
        configMap:
          name: sonarqube-sonarqube-config
          items:
          - key: sonar.properties
            path: sonar.properties
      - name: install-plugins
        configMap:
          name: sonarqube-sonarqube-install-plugins
          items:
          - key: install_plugins.sh
            path: install_plugins.sh
      - name: copy-plugins
        configMap:
          name: sonarqube-sonarqube-copy-plugins
          defaultMode: 493
          items:
          - key: copy_plugins.sh
            path: copy_plugins.sh
      - name: sonarqube
        persistentVolumeClaim:
          claimName: sonarqube-sonarqube
      - name: tmp-dir
        emptyDir: {}
